#!/usr/bin/env bash

ts=`date +%Y-%m-%dT%H:%M:%S`
val=${2:-0}
tsdir="${HOME}/.ts"
jfile="${tsdir}/.ts-data"
tsfile="${tsdir}/ts-data"

mkdir -p "${tsdir}"
touch "${jfile}"

IFS='|' read -ra PARTS < "${jfile}"
if [ ! -z "${PARTS[1]}" ]; then
  PARTS[1]="${ts}"
  PARTS[3]="${1:-${PARTS[3]}}"
  PARTS[4]=$((${val} + ${PARTS[4]}))
  out=$(IFS='|'; echo "${PARTS[*]}")
  echo "$out"  >> "${tsfile}"
  echo "" > "${jfile}"
else
  echo "No current task"
  exit 1
fi
